import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'

export default function Home() {
  const { push } = useRouter();
  
  useEffect(() => {
    push("/dashboard")
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-full flex justify-center items-center'>
        <p className='text-xl'>Home</p>
      </main>
    </>
  )
}
