/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 GLB.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

function TruckModel(props: any) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/3ds/3dtruck.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -2, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes['MediumTruck_Closed-Mat'].geometry} material={materials.Mat} />
        <mesh geometry={nodes['MediumTruck_Closed-Mat1'].geometry} material={materials['Mat.1']} />
      </group>
    </group>
  )
}

export default TruckModel

useGLTF.preload('/3ds/3dtruck.glb')
